### PR TITLE
Fix: only transmit CAN frame on valid opcode AND always send a status message upon attempted CAN transmit

### PR DESCRIPTION
**Pull request by aentinger**

### CODE REVIEW

**Review by facchinm — APPROVED** [review]

**Comment by facchinm** [comment]
After applying this patch I always get `write: No buffer space available` on Linux side after calling something like `./cansend can1 300#AC.AB.AD.AE.75.49.1A` . Is there maybe another patch to be applied on the other side?

**Comment by aentinger** [comment]
I even get this message without the patch. That's why I say that CAN is broken ...

**Comment by facchinm** [comment]
With this patch only https://github.com/arduino/portentax8-stm32h7-fw/commit/8c6e6e29c038622f32689f5bd7577fd9a463ab19 and https://github.com/arduino/meta-partner-arduino/commit/dabb3118f9c029617c5a6230e076ae553a9bff1d on the linux side I was able to send any amount of packets :upside_down_face:

**Comment by aentinger** [comment]
I'll be merging this, because this patch is essentially bug-free, the problem is somewhere where in the can driver handling.

Also this firmware will not be pulled into the X8 image, as long as https://github.com/arduino/meta-partner-arduino/blob/main/recipes-kernel/linux-firmware/linux-firmware-arduino-portenta-x8-stm32h7_git.bb#L19 is not updated.

**Pull request merged**
